services:

  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/${KEYCLOAK_REALM_NAME}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_AUDIENCE=ecommerce-api
    ports:
      - "5050:5050"
    networks:
      - ecommerce-network
    depends_on:
      flyway:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      keycloak:
        condition: service_started

  postgres:
    image: postgres:16-alpine
    container_name: db-ecommerce
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5051:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway
    container_name: flyway-migrator-ecommerce
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
    command: migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - ecommerce-network
    depends_on:
      postgres:
        condition: service_healthy


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ecommerce
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5052:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ecommerce-network
    depends_on:
      - postgres

  redis:
    image: redis:8.2.2
    container_name: redis-cache-ecommerce
    ports:
      - 5053:6379
    volumes:
      - redis_data:/data
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: keycloak/keycloak:26.0
    container_name: keycloak-ecommerce
    command:
      - start
      #- --optimized
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${POSTGRES_DB_KEYCLOAK}
      KC_DB_USERNAME: ${POSTGRES_USER_KEYCLOAK}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD_KEYCLOAK}
      KC_HOSTNAME: http://localhost:5054
      KC_HTTP_PORT: 8080
      KC_PROXY: edge
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "5054:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - ecommerce-network


  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB_KEYCLOAK}
      POSTGRES_USER: ${POSTGRES_USER_KEYCLOAK}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_KEYCLOAK}
    ports:
      - "5055:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_KEYCLOAK} -d ${POSTGRES_DB_KEYCLOAK}" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  ecommerce-network:
    driver: bridge


volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  keycloak_data: